### ISSUE TITLE
Buoyancy: Basics. main checklist

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/buoyancy-basics#1]
# Buoyancy: Basics main checklist

## Design

- [x] **Sim folder and design doc created** (Date: 03/08/24)
  - [x] Create sim folder
    in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs
    account
  - [x] Place [design doc](https://docs.google.com/document/d/1XH0LhgFuor4dfc0gfF96Ao-qk7771vRLn53jQplDe0I/edit?usp=sharing) in the sim folder
- [x] **Review user feedback**
  - [x] *If a
    Port:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=677625918)
  - [x] *If a new
    sim:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=898967246)
- [x] **Learning goals and standards identified** (Date: 03/08/24)
- [x] **Design concept complete**  (Date: 03/08/24)
- [ ] **Wireframes complete** (Date: //)
- [x] **Mockups complete** (Date: 03/08/24)
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion**
- [x] **Interviews complete** (Date: 11/jun/2024)
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 27/jun/2024)
  - [x] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [ ] **Prototype items**
  - [ ] Auxiliary screenshots (at least 1 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL) as appropriate
  - [ ] Email/Twitter announcement language
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Send Simulation Notification from the Admin page (to alert translators)
- [ ] **Pre-publication items**
  - [x] Auxiliary screenshots (up to 3 additional)
  - [ ] Screen-specific screenshots for metadata service (
    see [naming convention](https://github.com/phetsims/website/issues/1322#issuecomment-1010320827))
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Accessibility features
  - [ ] [Draft the Email announcement language](https://github.com/phetsims/tasks/issues/new?assignees=&labels=tasks%3Aemail&projects=&template=sim-announcement-email.md&title=Sim+Announcement+Email)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each
    screen created and uploaded to Drive
  - [ ] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429)
    for each screen (description, vocab words, questions for before/after sim use)
- [ ] **Make sim visible on website**
  - [x] Clear "Metadata caches" on
    the [Basic Administration Caches](https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminCachesPage)
    page
- [ ] **Post-publication items**
  - [ ] *If a Port:* Review legacy gold star activities, copy over if appropriate
  - [x] Share new features, design challenges, and treats with group!
  - [ ] Email announcement
  - [ ] Deliver
    to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Create "sim primer" issue
  - [x] Hold postmortem if applicable (Date: //)
  - [x] Send Simulation Notification from the Admin page (to alert translators)

## Inclusive Features

- [x] Alternative Input (Started: ) (Completed: )
  - [x] Interactive Highlights
  - [ ] Separate ScreenView controls into play area PDOM vs control area PDOM
- [x] Sound & Sonification (Completed: )
  - [ ] Sound design requirements determined: date: //
  - [ ] Sound design complete: date: //
  - [x] UI Sounds implemented: date: //
  - [ ] All sounds implemented: date: //
- [ ] Interactive Description - (link to description design & implementation checklist)
  - [ ] Description design complete (Started: ) (Completed: )
  - [ ] Development complete (Started: ) (Completed: )
  - [ ] Mobile description included
- [ ] Voicing - (include links to relevant voicing design document)

## Implementation

- [x] **Repository created** by @AgustinVallejo 
  following [new-repo-checklist.md](https://github.com/phetsims/phet-info/blob/main/checklists/new-repo-checklist.md) (
  Date: March 8th 2024)
- [x] **Development started** (Date: March 8th 2024)
- [x] **QA team "first look"** (Date: June 11th 2024)
- [ ] **Sim is "feature complete"** (Date: //)
- [ ] Interviews may happen around here (see above)
- [x] **Sim team sign-off** (Date: //)
- [x] **Code review completed** (Date: //)
- [x] **Sim dev test completed** (Date: //)
- [x] **Sim RC tests completed** (Date: //)
- [ ] **Pre-publication items**
  - [ ] Main screenshot (read [this](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md#screenshots))
  - [ ] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks -
    see [conventions](https://github.com/phetsims/joist/blob/main/js/CreditsNode.js))
  - [ ] Add CT tests for public query parameters that need testing. See examples
    in [listContinuousTests.js](https://github.com/phetsims/perennial/blob/main/js/listContinuousTests.js)
- [ ] **Published** (Date: //)

## QA

- [ ] *If a Port:* **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing started** (Date: //)
- [x] **Dev testing completed** (Date: //)
- [ ] **First RC published** (Date: //)
  - [ ] Test matrices put
    in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: //)
